---
title: "Teaching"
author: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

## 2020

- [Introduction to R](https://ivanek.github.io/introductionToR/), University of Basel, Switzerland (online)
- [Summer School in Bioinformatics and High-Dimensional Statistics](http://www3.unimedizin-mainz.de/transmed/training-program/training-in-scientific-skills/summer-school-in-bioinformatics-and-high-dimensional-statistics.html), Mainz, Germany (online)
- [~~Statistical data analysis for genome scale biology (CSAMA 2020)~~](https://www.huber.embl.de/csama2020/#home), Brixen, Italy (cancelled due to covid-19)
- [~~Bioinformatics summer school~~](https://uclouvain-cbio.github.io/BSS2020/), Louvain-la-Neuve, Belgium (cancelled due to covid-19)
- [Advanced topics in single-cell transcriptomics](https://www.sib.swiss/training/course/2020-05-adv-scrna), Basel, Switzerland (online)
- ~~RNA-seq analysis~~, University of Freiburg, Germany (postponed due to covid-19)
- [Analysis of genomics data with R/Bioconductor](https://ivanek.github.io/analysisOfGenomicsDataWithR/), University of Basel, Switzerland (online)

## 2019

- [Single-cell analysis autumn school](https://nbisweden.github.io/single-cell_sib_scilifelab/README.html), Leysin, Switzerland
- [Introduction to R](https://ivanek.github.io/introductionToR/), University of Basel, Switzerland
- [Statistical data analysis for genome scale biology (CSAMA 2019)](https://www.huber.embl.de/csama2019/#home), Brixen, Italy
- [Bioinformatics summer school](https://uclouvain-cbio.github.io/BSS2019/), Louvain-la-Neuve, Belgium
- [RNA-sequence analysis](https://www.ebi.ac.uk/training/events/2019/rna-sequence-analysis), EBI, Hinxton, UK
- [Analysis of genomics data with R/Bioconductor](https://ivanek.github.io/analysisOfGenomicsDataWithR/), University of Basel, Switzerland
- [Microbiota Data Analysis Workshop](http://gdc-mda.ethz.ch/MDA19/program.html), Zurich, Switzerland

## 2018

- [Statistical data analysis for genome scale biology (CSAMA 2018)](http://www-huber.embl.de/csama2018/#home), Brixen, Italy
- [Advanced RNA-seq analysis](https://www.ebi.ac.uk/training/events/2018/advanced-rna-seq-analysis), EBI, Hinxton, UK

## 2017

- [Statistics for Life Scientists](https://www.sib.swiss/training/course/stats-basel2017), Basel, Switzerland
- [Statistical data analysis for genome scale biology (CSAMA 2017)](http://www.huber.embl.de/csama2017/#home), Brixen, Italy
- [Advanced RNA-seq and ChIP-seq data analysis](http://www.ebi.ac.uk/training/events/2017/advanced-rna-seq-and-chip-seq-data-analysis-1), EBI, Hinxton, UK

## 2016

- Advanced course on edgeR and DESeq2, Leuven, Belgium
- [Statistics for Life Scientists](http://edu.isb-sib.ch/course/view.php?id=269), Basel, Switzerland
- [Method course - Analysis of NextGen RNA-seq data for expression profiling and protein-binding RNAs](http://www.uni-regensburg.de/medicine/statistical-bioinformatics/method-course-oct-16/program/index.html), Regensburg, Germany
- [Analysis of high-throughput sequencing data](http://events.embo.org/16-htp-seq/), Cambridge, UK
- [Statistics and computing in genome data science (CSAMA 2016)](http://www.huber.embl.de/csama2016/about/), Brixen, Italy

## 2015
- Statistical transcriptomics data analysis: from design to reproducible research, Fribourg, Switzerland
- [Statistical techniques for genomics/life sciences](http://edu.isb-sib.ch/course/view.php?id=189), Basel, Switzerland

## 2014
- [Multivariate analysis for exploration and visualisation of biological data](http://edu.isb-sib.ch/course/view.php?id=187), Lausanne, Switzerland
- [Introduction to classification](http://edu.isb-sib.ch/course/view.php?id=186), Lausanne, Switzerland
- [Advanced statistics:statistical modeling](http://edu.isb-sib.ch/course/view.php?id=177), Lausanne, Switzerland
- [Microarray and RNAseq data analysis with R](http://edu.isb-sib.ch/course/view.php?id=175), Fribourg, Switzerland
- RNA-seq data analysis, Brno, Czech Republic
- [RNA-seq: from experiment planning to statistical data analysis](http://www.bc2.ch/courses/RNASeqCourseBasel201401/), Basel, Switzerland

## 2013
- [RNA-seq: from experiment planning to statistical data analysis](http://biologie.cuso.ch/staromics/activities/detail-activity/item/courses/rna-seq-from-experiment-planing-to-statistical-data-analysis/), Bern, Switzerland
- [Multivariate analysis for exploration and visualisation of biological data](http://edu.isb-sib.ch/course/view.php?id=150), Lausanne, Switzerland
- [Advanced transcriptomics analysis](http://edu.isb-sib.ch/course/view.php?id=146), Lausanne, Switzerland
- [Introduction to statistics for biologists](http://edu.isb-sib.ch/course/view.php?id=147), Lausanne, Switzerland

## 2012
- [Integration of data from different omics](http://edu.isb-sib.ch/course/view.php?id=124), Lausanne, Switzerland
- [Analysis of differential gene expression](http://edu.isb-sib.ch/course/view.php?id=120), Lausanne, Switzerland
- [Multivariate analysis for exploration and visualisation of biological data](http://edu.isb-sib.ch/course/view.php?id=121), Lausanne, Switzerland

